### ISSUE TITLE
lists in input source field can cause trouble

### ISSUE THREAD

**Issue by KerstenBreuer** [rabix/composer#339]
I experience very uninformative errors when running my rabix-compsed workflow with toil.
As I reported in the corresponding issue (https://github.com/BD2KGenomics/toil/issues/2022), the cause is that rabix composer specifies the input sources as lists:

```
steps:
  validate_data:
    in:
      feat_in:
        source: 
          - feat_in
      label_in:
        source: 
          - label_in
      metadata_in:
        source: 
          - metadata_in
    out:
      - validated_feat
      - validated_label
      - validated_metadata
    run: ../tools/01_validate_data.cwl
```
However, toil only likes this if you use the `linkMerge` method, which of cause makes sense. Even though cwltool seems to have no problem with this, I think it would make sense to change the behavior to this:
```
steps:
  validate_data:
    in:
      feat_in:
        source: feat_in
      label_in:
        source: label_in
      metadata_in:
        source: metadata_in
    out:
      - validated_feat
      - validated_label
      - validated_metadata
    run: ../tools/01_validate_data.cwl
```
(The same also applies to the `outputSource` fields.)

Or is there another case in which listing of inputs might be useful which I am missing right now?
