### ISSUE TITLE
Allow stdout, stderr as output types

### ISSUE THREAD

**Issue by TMiguelT** [rabix/composer#396]
CWL 1.0 lets you do something like:

```yaml
outputs:
  an_output_name:
    type: stdout

stdout: a_stdout_file
```

Which is much more concise than

```yaml
outputs:
  an_output_name:
    type: File
    streamable: true
    outputBinding:
      glob: a_stdout_file

stdout: a_stdout_file
```

It is explained here in the spec: https://www.commonwl.org/v1.0/CommandLineTool.html#stdout

Could something like this be implemented?
