### ISSUE TITLE
Optionally allow dictionary yaml syntax 

### ISSUE THREAD

**Issue by TMiguelT** [rabix/composer#398]
Many fields in CWL can be specified either as a dictionary, or as an array. For example, steps in a workflow could be

```yaml
  bwa:
    in: {}
    out: {}
    run: ''

  sort:
    in: {}
    out: {}
    run: ''
```

or they could be

```yaml
  - id: bwa
    in: {}
    out: {}
    run: ''

  - id: sort:
    in: {}
    out: {}
    run: ''
```

Rabix automatically converts the dictionary form to the list form in all cases. Could it be possible to have a setting that configures which YAML output we would like? The dictionary is more concise in most cases, and I would like this option so that it doesn't change the structure of my hand-written CWL.
