### ISSUE TITLE
Item Separator in inputBinding should be arbitrary string

### ISSUE THREAD

**Issue by kaushik-work** [rabix/composer#414]
We should be able to use an arbitrary string as an item separator. This is to enable the use case where we have the command line being like `-I a.txt -I b.txt -I c.txt` with the raw CWL being like

```
  - id: input
    type: 'File[]?'
    inputBinding:
      position: 0
      prefix: '-I'
      itemSeparator: ' -I '
```
