### ISSUE TITLE
Path generation on windows: "..\" insteat of "../"

### ISSUE THREAD

**Issue by KerstenBreuer** [rabix/composer#434]
When I add a command line tool to a workflow on windows, I am getting an invalid path:

```
  - id: tn5_overhang_correction
    in:
      - id: bam
        source: sorting_bam/bam_sorted
    out:
      - id: bam_tn5_corrected
    run: ..\tools/tn5_overhang_correction.cwl
```
The correct path should be ` ..\tools/tn5_overhang_correction.cwl`
